name: food
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  collection: ^1.18.0
  flutter_credit_card: ^4.0.1
  intl: ^0.19.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  lottie: ^2.0.0 # Add this line for Lottie support
  device_preview: ^1.1.4
  carousel_slider: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/burgers/
    - lib/images/sides/
    - lib/images/salads/
    - lib/images/drinks/
    - lib/images/desserts/
    
